# .streamlit/secrets.toml

SUPABASE_URL = "https://jagzzokffoqqunjvkdyk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZ3p6b2tmZm9xcXVuanZrZHlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTE2NjY4NywiZXhwIjoyMDc0NzQyNjg3fQ.Iu0ski4A0-g4I9rBJkPGjGgE5jPEhFbuUvT8j0T3MzM"
# .streamlit/secrets.toml
user = "postgres.jagzzokffoqqunjvkdyk"
password = "SUA_SENHA_REAL"
host = "aws-1-us-east-1.pooler.supabase.com" 
port = "6543"
dbname = "postgres"
