SUPABASE_URL = "https://sdfdeghaxbxqhornmdgu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZmRlZ2hheGJ4cWhvcm5tZGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MDI4NzAsImV4cCI6MjA3NTE3ODg3MH0.8vnMKvbJzCm2Wb6pjgNVTvpByrY_-6WNz8XqM5vuHkc"
